(async()=>{
 const $=id=>document.getElementById(id),make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e},glyph={yellow:'🟨',blue:'🟦',green:'🟩'},key='aeqr-registry-board-v1';
 function action(text,fn){const b=make('button',text);b.type='button';b.onclick=fn;return b}
 function view(id){['catalog','board','sources'].forEach(v=>$(v).hidden=v!==id);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===id)))}
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('close-detail').onclick=()=>$('detail').close();
 let registry;try{const r=await fetch('./registry.json');if(!r.ok)throw Error('HTTP '+r.status);registry=await r.json()}catch(e){$('summary').textContent='Registry unavailable: '+e.message;return}
 const entries=registry.entries,known=new Map(entries.map(e=>[e.id,e]));let cards=[],storageProblem=false;
 try{const raw=localStorage.getItem(key);if(raw!==null){const data=JSON.parse(raw);if(!Array.isArray(data)||data.length>100)throw Error();cards=data.map(c=>aeQRCard.validate(c,known));if(new Set(cards.map(c=>c.id)).size!==cards.length)throw Error()}}catch{storageProblem=true;$('save-status').textContent='Saved data could not be read; it has not been overwritten. Export before changing this board.'}
 function save(){try{localStorage.setItem(key,JSON.stringify(cards));storageProblem=false;$('save-status').textContent='Saved in this browser only.'}catch{storageProblem=true;$('save-status').textContent='Storage unavailable. Export JSON to keep your work.'}}
 function download(name,type,data){const u=URL.createObjectURL(new Blob([data],{type})),a=make('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 $('export-board').onclick=()=>download('aeqr-kaenbaen.json','application/json',JSON.stringify(cards,null,2));
 function qr(url,parent){const q=qrcode(0,'M');q.addData(url);q.make();const box=make('div');box.className='qr';box.innerHTML=q.createSvgTag({cellSize:4,margin:16,scalable:true});parent.append(box,make('p',url),action('Download QR SVG',()=>download('aeqr.svg','image/svg+xml',q.createSvgTag({cellSize:8,margin:32,scalable:true}))));}
 function dialog(){const d=$('detail-body');d.replaceChildren();if(!$('detail').open)$('detail').showModal();return d}
 function add(card){if(cards.length>=100)throw Error('Board limit: 100 cards.');const c=aeQRCard.validate(card,known);if(cards.some(x=>x.id===c.id))throw Error('Card already exists.');cards.push(c);save();renderBoard();return c}
 function plant(entry){const c=add({v:1,id:crypto.randomUUID(),entry_id:entry.id,title:entry.name.slice(0,80),purpose:entry.purpose,stage:'audit',notes:entry.functional.status==='blocked'?'Review the recorded blockers before planning execution.':''});$('detail').close();view('board');cardDetail(c)}
 function detail(e){const d=dialog();d.append(make('small',glyph[e.purpose]+' '+e.record_type+' / '+e.document_type),make('h2',e.name),make('p',e.description||e.purpose_basis));const a=make('a','Open canonical destination ↗');a.href=e.canonical_url;a.target='_blank';a.rel='noopener noreferrer';d.append(a,make('p','Availability: '+e.availability.status+' · Function: '+e.functional.status),make('p','Execute: '+e.authority.execute+' · QR grants no authority.'));
  if(e.declared_status)d.append(make('p','Catalog claim: '+e.declared_status));
  const skills=e.skill_ids||[];if(skills.length)d.append(make('p','Bound skills: '+skills.map(id=>known.get(id)?.name||id).join(', ')));
  d.append(make('p','Capabilities: '+(e.capabilities.join(', ')||'No capability claim')),make('p','Verification: '+(e.verified_at||'Not checked')+' · Source: '+e.source.revision));
  const evidence=make('details');evidence.append(make('summary','Dependencies and evidence'),make('pre',JSON.stringify({dependencies:e.dependencies,functional:e.functional,source:e.source},null,2)));d.append(evidence,action('Plant on kænbæn',()=>{try{plant(e)}catch(err){d.append(make('p',err.message))}}));qr(registry.base_url+'registry/#entry/'+e.id,d);
 }
 function cardDetail(card,imported=false){const c=aeQRCard.validate(card,known),d=dialog();d.append(make('h2',c.title),make('p',known.get(c.entry_id).name));
  if(imported){d.append(make('p','Shared snapshot. Review it before saving a local copy. Scanning has changed nothing.'),action('Save a copy',()=>{try{const copy=add({...c,id:crypto.randomUUID()});cardDetail(copy);view('board')}catch(e){d.append(make('p',e.message))}}));}
  else{const form=make('form');const title=make('input');title.value=c.title;title.maxLength=80;title.required=true;title.setAttribute('aria-label','Card title');const notes=make('textarea');notes.value=c.notes;notes.maxLength=280;notes.setAttribute('aria-label','Notes or evidence');form.append(title,notes);const submit=make('button','Save notes');submit.type='submit';form.append(submit);form.onsubmit=event=>{event.preventDefault();try{const updated=aeQRCard.validate({...c,title:title.value,notes:notes.value},known);cards=cards.map(x=>x.id===c.id?updated:x);save();renderBoard();cardDetail(updated)}catch(e){d.append(make('p',e.message))}};d.append(form,action('Remove card',()=>{if(confirm('Remove this local card?')){cards=cards.filter(x=>x.id!==c.id);save();renderBoard();$('detail').close()}}));}
  qr(registry.base_url+'registry/#card/'+aeQRCard.encode(c,known),d);
 }
 function renderBoard(){$('lanes').replaceChildren();aeQRCard.stages.forEach(stage=>{const lane=make('section');lane.className='lane';lane.append(make('h3',stage.toUpperCase()));const members=cards.filter(c=>c.stage===stage);if(!members.length)lane.append(make('p','No cards'));members.forEach(c=>{const box=make('article');box.className='task '+c.purpose;box.append(make('small',glyph[c.purpose]+' '+known.get(c.entry_id).name),make('h4',c.title));const s=make('select');s.setAttribute('aria-label','Stage for '+c.title);aeQRCard.stages.forEach(value=>{const o=make('option',value);o.value=value;s.append(o)});s.value=c.stage;s.onchange=()=>{cards=cards.map(x=>x.id===c.id?{...x,stage:s.value}:x);save();renderBoard()};box.append(s,action('QR + notes',()=>cardDetail(c)));lane.append(box)});$('lanes').append(lane)})}
 function renderEntries(){const q=$('search').value.toLowerCase(),type=$('record').value,purpose=$('purpose').value;const found=entries.filter(e=>(type==='all'||e.record_type===type)&&(purpose==='all'||e.purpose===purpose)&&[e.name,e.path,e.description,e.functional.status,...e.capabilities].join(' ').toLowerCase().includes(q));$('count').textContent=found.length+' / '+entries.length+' records';$('entries').replaceChildren();found.forEach(e=>{const box=make('article');box.className='entry '+e.purpose;box.append(make('small',glyph[e.purpose]+' '+e.record_type),make('h2',e.name),make('p','Available: '+e.availability.status),make('p','Function: '+e.functional.status),action('Context + QR',()=>detail(e)));$('entries').append(box)})}
 ['search','record','purpose'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderEntries));$('summary').textContent=entries.length+' records · '+entries.filter(e=>e.record_type==='surface').length+' pages · '+entries.filter(e=>e.functional.status==='blocked').length+' with recorded blockers';renderEntries();renderBoard();
 function route(){try{const [type,payload]=location.hash.slice(1).split('/');if(type==='entry'){const e=known.get(payload);if(!e)throw Error('Unknown registry entry.');detail(e)}else if(type==='card'){cardDetail(aeQRCard.decode(payload,known),true)}}catch(e){dialog().append(make('p',e.message))}}
 window.addEventListener('hashchange',route);route();
})();
